### ISSUE TITLE
I don't see button for save changes in config

### ISSUE THREAD

**Issue by Kirill** [mantisbt-plugins/BBCodePlus#1]
In config of plugins don't exist button for save changes.
![2015-09-22 11_25_39](https://cloud.githubusercontent.com/assets/302940/10014883/ae235ed4-611c-11e5-945b-d0d76e9da766.png)

**Comment by bkraul** [comment]
This has been corrected, and changes have been pushed.Thank you for pointing it out.

Best regards,

Belman Kraul
