### ISSUE TITLE
list numbering operation

### ISSUE THREAD

**Issue by priocomdevops** [mantisbt-plugins/BBCodePlus#102]
Is it possible to create numbered lists like in here in GitHub? 

 i.e. you select 'Add list', it creates first bullet/number then you simply press enter to create more? 

Would be much simpler instead of typing first, highlighting them then pressing the 'Add list' button, as is the case presently.

Otherwise many thanks for the plugin, it is fantastic.

**Comment by bkraul** [comment]
@priocomdevops, GitHub's markdown editor is what you'd consider semi-wysiwyg. BBCodePlus is based on a purely raw editor with helpers to generate the BBCode markup, much like the BBCode editors of old. Adding the behavior you describe is unfortunately beyond the design scope of the plugin.
