### ISSUE TITLE
Bulleted list appears as numeric list

### ISSUE THREAD

**Issue by mfernau** [mantisbt-plugins/BBCodePlus#14]
If I add a bulleted list to my note it appears as an numeric list.

![mantis_bb_edit](https://cloud.githubusercontent.com/assets/9843274/18224726/dea79136-71df-11e6-9ccc-fe248df17fc4.png)
![mantis_bb_result](https://cloud.githubusercontent.com/assets/9843274/18224727/e75807ac-71df-11e6-92a2-fc6f5a3bf43b.png)

I use mantisbt 1.3.1 - maybe there changed something in the depth of css:
![mantis_bb_css](https://cloud.githubusercontent.com/assets/9843274/18224764/b51a922c-71e0-11e6-8b3b-e6078879151d.png)

Why not using ul-Element?

**Comment by bkraul** [comment]
Thanks for the report. This has been corrected. We are still using the ol element because the bbcode notation is shared with the ordered list, but it now works correctly by using a CSS class.
