### ISSUE TITLE
Clarification: No MarkDown support?

### ISSUE THREAD

**Issue by sagamusix** [mantisbt-plugins/BBCodePlus#15]
There is an option "Enable MarkDown editor". However, as far as I understand, MarkItUp **can** support MarkDown, but in this plugin it is **only** configured to support BBCode. So, either it has to be clarified how MarkDown can be used, or the option has to be renamed to something like "Enable visual editor".

**Comment by bkraul** [comment]
You are correct. I have changed the description of the editor as strictly a BBCode editor.

I do have an interest in developing a separate markdown plugin, but it is not a high priority at the moment.
