### ISSUE TITLE
bbcode support for mantisbt 2.x ?

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/BBCodePlus#17]

**Comment by rebine** [comment]
I did
`git checkout master-2.0.x`

But preview.php has echo shortcut syntax. I got error on my environment (php5.4.X).

http://php.net/manual/en/function.echo.php
> echo also has a shortcut syntax, where you can immediately follow the opening tag with an equals sign. Prior to PHP 5.4.0, this short syntax only works with the short_open_tag configuration setting enabled.

It replaced '<?=' to '<?php echo' when I use.
plz update it developer team.

**Comment by luzpaz** [comment]
CC @dregad

**Comment by luzpaz** [comment]
@rebine please change description to indicate that
![sceenshot](https://cloud.githubusercontent.com/assets/4140247/23019464/7d5a98de-f410-11e6-9a35-442550260dda.png)

**Comment by Kirill** [comment]
For mantisbt 2.x need PHP 5.5.9+
Please read https://github.com/mantisbt/mantisbt/tree/master-2.0.x#requirements

**Comment by rebine** [comment]
@luzpaz 
I'm not member.

@Kirill 
OK.I'm mistake and set short_open_tag on .
