### ISSUE TITLE
The '=' in [code=][/code] breaks the bbcode render if no language is specified

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/BBCodePlus#21]
MantisBT 2.4.1.
Bbcode plugin (latest I assume)

Example: https://freecadweb.org/tracker/bug_revision_view_page.php?bugnote_id=9154

Reproduce: 
1. Click code button
Result: overlay screen with dialog appears asking what coding language
2. Press OK
Result: `[code=][/code]` is printed 
3. Add text between brackets and then press 'Add Note'
Result: text won't be rendered in bbcode

Suggested outcomes:
A. After step 2 markup doesn't include '=' ex. `[code][/code]`
or
B. After step 3 the `[code=][/code]` renders markup correctly even though language was not specified.

Edit: Downstream ticket https://freecadweb.org/tracker/view.php?id=3047

**Comment by luzpaz** [comment]
CC @bkraul

**Comment by luzpaz** [comment]
Bump

**Comment by luzpaz** [comment]
@Kirill care to weigh in?

**Comment by luzpaz** [comment]
@bkraul do you mind pushing another release so we can run your newest changes ?

**Comment by bkraul** [comment]
Not sure what you mean @luzpaz, All branches of the project have the latest changes. All you'd need to do is download the latest master-x.x.x.

**Comment by luzpaz** [comment]
@bkraul see https://github.com/mantisbt-plugins/BBCodePlus/releases 
it shows last release was 1.0.11

**Comment by bkraul** [comment]
This is done.
