### ISSUE TITLE
Feature Request: can [quote=bkraul] actually work like @bkraul

### ISSUE THREAD

**Issue by luzpaz** [mantisbt-plugins/BBCodePlus#22]
When quoting someone is it possible to also trigger a @bkraul mention?

**Comment by luzpaz** [comment]
Bump

**Comment by bkraul** [comment]
Can you elaborate on this? 

Are you implying that a notification needs to be sent to whoever is being quoted if it is found to be an existing user, and create a link to the user's profile?

If so, I'm thinking It is kinda beyond the scope of the plugin, but I suppose it would be worth looking into it.

**Comment by luzpaz** [comment]
> Are you implying that a notification needs to be sent to whoever is being quoted if it is found to be an existing user   

Yes! Is it beyond the scope though? In forums that I've seen like phpbb that is exacrly how the [quote] bbcode works.

**Comment by bkraul** [comment]
To my understanding, from recent work I had to do on this, you can trigger this simply by using @user . How you would do it with the quote would be something like this:
```
[quote]@bkraul : This is some content[/quote]
```
Would that not satisfy your request?

**Comment by luzpaz** [comment]
Sure
