### ISSUE TITLE
<br> Tag replacement

### ISSUE THREAD

**Issue by MrBlockenpfeffer** [mantisbt-plugins/BBCodePlus#25]
When using ```xml``` to Highlight XML in the Bugnotes it seems that all tags that are starting with "<br" are replaced. 

Even if all possible fields on the options page are set to "no" the plugin replaces this tags. The 2.0 master branch is used.

![mantisxml](https://user-images.githubusercontent.com/22150591/28916545-d9652a0c-7842-11e7-9a13-4f01d63af1d4.PNG)

**Comment by bkraul** [comment]
@MrBlockenpfeffer: A new version of BBCodePlus has been released with a brand new parser system that should address your issue. This version is for MantisBT 2.x.

You are welcome to download the latest [release](https://github.com/mantisbt-plugins/BBCodePlus/releases).
