### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rudddy** [mantisbt-plugins/BBCodePlus#28]
Hye

thanks for your plugin.

How can I install it ?

I didn't see install instructions. Just copy BBCodePlus folder in my /plugins folder ?

Thanks

**Comment by bkraul** [comment]
First, make sure you are downloading the correct plugin for your version of MantisBT.

Then, copy the BBCodePlus folder (not the main but the inner folder) to your plugins directory). The resulting structure should look like this:
```
plugins
|---BBCodePlus
      |---files
      |---lang
      |---pages
      |---BBCodePlus.php
```

Then, go to your administration, and plugins, and activate it. To avoid compatibility issues, disable the following plugins:

* URL Processing.
* MantisBT internal links.

**Comment by rudddy** [comment]
thanks
