### ISSUE TITLE
url in td does not format correctly. 

### ISSUE THREAD

**Issue by jacksnodgrass** [mantisbt-plugins/BBCodePlus#29]
[table]
[tr]
[td][url]https://google.com[/url][/td]
[/tr]
[/table]

does not work. 
it  shows up exactly as: 
[td][url]https://google.com[/url][/td]
... 

- jack

**Comment by bkraul** [comment]
@jacksnodgrass: A new version of BBCodePlus has been released with a brand new parser system that should address your issue. This version is for MantisBT 2.x.

You are welcome to download the latest [release](https://github.com/mantisbt-plugins/BBCodePlus/releases).
