### ISSUE TITLE
Default "process email" option results in broken emails

### ISSUE THREAD

**Issue by hraftery** [mantisbt-plugins/BBCodePlus#30]
Fresh install of BBCode+ 2.0.15 on MantisBT 2.15.0 using PHPMAILER_METHOD_SMTP to send emails. After install, general administration email come through HTML encoded but Content-Type is still text/plain, so email appears garbled.

For example, after install of the plugin, an email looks like so:

```
<earlier headers snipped>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

The following account has been created:<br />
<br />
Username: user<br />
E-mail: user@domain<br />
Remote IP address: 1.1.1.1<br />
<a target=3D"_blank"
href=3D"http://issues.domain.name/">http://issues.domain.name/</a><br=
 />
<br />
Do not reply to this message
```

If the content happens to include a URL with an ampersand (eg. an account activation email), then the URL is no longer clickable or copy-pastable. The HTML encoding has to be undone first.

Changing the "Process email" option to "No" rectifies the situation, but I assume results in uglier emails which contain content from issues with BBCode in them.

Is this is a matter of BBCodePlus assuming MantisBT is sending HTML formatted emails?

**Comment by bkraul** [comment]
I believe this relates to #10. I will have to go over the 2.15 code to see if Mantis ever came to support the option of HTML. The BBcode artifacts should not be showing. Will get back with you on this.

**Comment by atrol** [comment]
> see if Mantis ever came to support the option of HTML.

Not supported, see https://www.mantisbt.org/bugs/view.php?id=1400

**Comment by bkraul** [comment]
That's what I thought. Thank you, @atrol

**Comment by bkraul** [comment]
Closing this one as wontfix, due to HTML email not being available on mantis as of yet.
