### ISSUE TITLE
Bulleted and numberd lists problem with multiple elements em insted of li

### ISSUE THREAD

**Issue by dasanselmo** [mantisbt-plugins/BBCodePlus#33]
MantisBT 2.19.0
BBCode+ 2.0.15

Somehow if a list has multiple elements, it's rendered em tag not li, see attached image:
![bbcode_bulletedlit_problem](https://user-images.githubusercontent.com/46569890/53238494-a81ed580-3699-11e9-9801-86df5474c244.png)

**Comment by bkraul** [comment]
What is the exact Bbcode/content you are using?

**Comment by dasanselmo** [comment]
Here are the bbcode settings:
![bbcode_settings](https://user-images.githubusercontent.com/46569890/53241360-c1c41b00-36a1-11e9-91eb-5e5c75e53e4b.png)

Only MantisBT Formatting 2.19.0 is a related plugin what we use.

**Comment by bkraul** [comment]
I was meaning what is the exact bbcode notation/code you are using that ends up rendering that result?

**Comment by dasanselmo** [comment]
sorry - here it is:
![bbcode_ineditor](https://user-images.githubusercontent.com/46569890/53241635-8b3ad000-36a2-11e9-83aa-30bdbe5fa8bd.png)

**Comment by bkraul** [comment]
The endings to the list items (marked by `[/*]`) you have on the first list are not part of the list item notation, and not supported. This is breaking the rendering of your list items.

If you type this:
```
item 1
item 2
item 3
```

And then select the text and press the 
![image](https://user-images.githubusercontent.com/14616851/53241874-a688e980-3668-11e9-9377-dc43aea704aa.png) button, you will see that the resulting BBCode will be:
```
[list]
[*]item 1
[*]item 2
[*]item 3
[/list]
```

**Comment by dasanselmo** [comment]
Sorry, you have right. that was just a try to fix it. anyway i did exactly what you said and the results are still not ok.
![bbcode_ineditor_to_layout](https://user-images.githubusercontent.com/46569890/53247480-c72a6100-36b3-11e9-8a00-4087f0bed19e.png)

**Comment by bkraul** [comment]
Could you please try a fresh copy of [master-2.0.x](https://github.com/mantisbt-plugins/BBCodePlus/tree/master-2.0.x) to see if this resolves your issue? I am assuming that 2.x is the version of mantis you are using.

I tested with the latest `master-2.0.x` (`2.0.17`) on mantisbt 2.19, and the list items show up properly.

**Comment by bkraul** [comment]
Your issue seems to be that you have **Markdown Processing** enabled on the Mantis Formatting plugin. BBCodePlus does not run well with that feature enabled, as it is a completely different parser. In Markdown, a notation such as `[*]` would translate as `[` followed by an emphazised  string (italics, which are `*like this*` in Markdown) , which is what is happening here.

You are welcome to download the latest [release](https://github.com/mantisbt-plugins/BBCodePlus/releases) which incorporates a system notice for when the Markdown is turned on.

**Comment by dasanselmo** [comment]
You had right. Thanks for the patch and fast reply.
