### ISSUE TITLE
Invalid markup in plugin's config page

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/BBCodePlus#48]
Probably a missing, extra or misplaced closing `</div>` tag

![image](https://user-images.githubusercontent.com/449891/54668061-3e55e800-4aee-11e9-843e-2260f022266e.png)  

![image](https://user-images.githubusercontent.com/449891/54668097-52014e80-4aee-11e9-8d55-0bce47e533ef.png)

This is with current _master_ branch (b8810d10fbc049cc13462e275467c3cdf2ad2178)

**Comment by bkraul** [comment]
@dregad so the behavior being caused is duplication of a side toolbar item? ~~Which version of MantisBT are you testing with?~~ I have checked the `<div>` nesting on the plugin's config file and could find no issues with un-closed `</div>` tags. I also do not see the that one book-looking toolbar item, and nothing else shows duplicated.

![image](https://user-images.githubusercontent.com/14616851/54679901-75b89a80-4ad6-11e9-9c53-c5969d29d37c.png)

**Comment by bkraul** [comment]
I must be blind. From your screenshot I see you are testing with Mantis 2.21-dev. My screenshot is from master (version 2.19.1, according to `core/constant_inc.php`). Setting up a testing environment with master-2.20.

**Comment by dregad** [comment]
For the record, I'm getting the same behavior on 2.19.1. I mentioned the closing div's because I've seen this behavior before and it is usually caused by invalid HTML markup. Could also be incorrect nesting.

**Comment by bkraul** [comment]
Just so that I can replicate, what is that book-looking toolbar item? I cannot see it even in the 2.21-dev env I just set up, which means it must be a plugin?

**Comment by dregad** [comment]
That's from 
```
$g_enable_project_documentation = ON;
$g_wiki_enable = ON;
```

**Comment by dregad** [comment]
Wait a minute, I just noticed I'm seeing this glitch on other pages as well, so it could be that it's not caused by BBCode+ after all. Let me check.

**Comment by bkraul** [comment]
I got you. For good measure, I took the rendered HTML from the config file and ran it through a [closing tag checker](https://www.aliciaramirez.com/closing-tags-checker/) and found no issues. I also enabled the documentation and wiki as you mentioned, and I still don't see the behavior. I have all stock plugins plus BBCodePlus enabled.

![image](https://user-images.githubusercontent.com/14616851/54682786-dbf4eb80-4add-11e9-9661-009b0dfe3a23.png)

**Comment by dregad** [comment]
OK so after uninstalling all plugins, I can confirm the behavior is caused by BBCode+ indeed, but not the config page itself.

Steps to reproduce
- fresh MantisBT install
- go to Manage Plugins page (only MantisCore + MantisBT Formatting are installed)
- footer displays correctly, next to sidebar
- install BBCode+
- footer displays behind sidebar (same behavior is visible on most other MantisBT pages)

So, maybe something in your headers.

**Comment by dregad** [comment]
This is it: https://github.com/mantisbt-plugins/BBCodePlus/blob/v2.1.1/BBCodePlus/BBCodePlus.php#L98

**Comment by dregad** [comment]
Sorry I meant to commit that to my fork and submit as a pull request, did not realize that I was on the main repo.

**Comment by bkraul** [comment]
Nice. Yeah, I can definitely see this having an extra `</div>`. However it would only show up if Mantis Formatting Markdown Processing is on. On my default fresh install of MantisBT 2.21.-dev, Markdown Processing was off by default, hence me not being able to see this.

No issues on the commit, on that, I rolled out a [guide ](https://github.com/mantisbt-plugins/BBCodePlus/wiki/Contributing-to-BBCodePlus) on forking and pull-requesting that might be helpful. The basic tenet of it is that we do not make commits directly to our fork's master but we work on develop and feature branches, keeping the master always in sync with upstream. Should make things easier in the long run when it comes to pull-requesting. Since this was not a PR but a direct commit by a maintainer, it should not be a problem at this point.

Thanks for correcting!

**Comment by dregad** [comment]
Yes that's what I usually do as well, it's just that I did not realize I was editing the file on the main repo, I thought I was on my fork... 🤪

Again sorry for not following the guidelines

**Comment by bkraul** [comment]
OK, so I went ahead and re-checked the tags after the fix, just to be sure. The `<div>` from the BBCodePlus plugin that shows the warning is now correct, but I am getting this nonetheless:

![image](https://user-images.githubusercontent.com/14616851/54689232-19ad4080-4aed-11e9-9c6a-cc8c17431a53.png)

No visible rendering issues are showing, though.

It might just be a problem of that one particular checker. I will try others.

**Comment by bkraul** [comment]
Nevermind on previous one. User error. All seems good.
