### ISSUE TITLE
PHP Notice:  Undefined variable: t_extra_link_tags 

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/BBCodePlus#56]
I noticed this in the PHP error log.

```
PHP Notice:  Undefined variable: t_extra_link_tags in .../BBCodePlus.php on line 269, referer: http://localhost:81/mantis/my_view_page.php
```

**Comment by bkraul** [comment]
Yeah I think it is a left over of the old code. `t_extra_link_tags` was used to force links to open on a new tab/window, overriding the MantisBT targets. Because the tags are now being added at plugin intialization, I have to review this process. Thanks for catching that!
