### ISSUE TITLE
Installing the plugin breaks issue link in notification emails

### ISSUE THREAD

**Issue by sachintha81** [mantisbt-plugins/BBCodePlus#64]
In a typical notification email a user gets when, for example, the status of an issue is changed, should look like the following:

`
http://mysite.com/mantis/view.php?id=1
`

However, when I install the latest version of BBCodePlus (Ver. 2.1.3), the link format changes to the following:

`
http://mysite.com/mantis#1
`

This is a problem since clicking the second link takes you to the user's `MyView` page, not directly to the issue.

Additional Info
---
![Capture](https://user-images.githubusercontent.com/8787573/58911810-876d0f80-86cd-11e9-9649-677b73a9a1eb.PNG)

**Comment by bkraul** [comment]
A new set of changes has been merged into the master. Please download master and check for correction of this issue with feedback.

**Comment by sachintha81** [comment]
Yes the updates has fixed the issue. Thanks!
