### ISSUE TITLE
Compatibility with PHP7 (preg_replace)

### ISSUE THREAD

**Issue by andrzejkupczyk** [mantisbt-plugins/BBCodePlus#8]
PHP Manual:

> As of PHP 5.5.0 E_DEPRECATED level error is emitted when passing in the "\e" modifier. As of PHP 7.0.0 E_WARNING is emited in this case and "\e" modifier has no effect.

This causes that issues/bugs are not displayed correctly.

**Comment by bkraul** [comment]
@andrzejkupczyk what version are you using? The use of the /e modifier is addressed in the current master for both 1.3 and 1.2. Are you using one of the tags?

**Comment by andrzejkupczyk** [comment]
Mantis v1.3. BBCodePlus v1.0.7. I'll check it again tonight.

**Comment by bkraul** [comment]
Please download latest release, 1.0.8.

**Comment by andrzejkupczyk** [comment]
Great, thanks!
