### ISSUE TITLE
Installing plugin breaks issue links in bug_view_inc

### ISSUE THREAD

**Issue by spmeesseman** [mantisbt-plugins/BBCodePlus#81]
The bug_view_inc.php displays the various sections/notes and produces urls for buglinks.  However, when this plugin's formatted() funtion is called when dsplaying the bug, it strips the a hrefs that the MantisBTFormatting plugin makes
![buglinksbug](https://user-images.githubusercontent.com/48744816/61888453-812b3080-aed1-11e9-97dd-2759955bee44.png)
.  Possibly related to #64?

BBCodePlus.php string_process_bbcode()

` if ( ON == $this->t_MantisCoreFormatting_process_urls ) {
            $p_string = string_strip_hrefs( $p_string );
         }`

**Comment by bkraul** [comment]
Which version are you using? the latest master (or latest release)?

**Comment by spmeesseman** [comment]
ah.  i believe i did a git clone to get this plugin, so yes the master branch.  ill double check that and post back if i'm wrong.  Should I grab the released version?  Whats the best way to tell which I have?  I really cant remember how I got this one Ive done so much installing the last several weeks

**Comment by bkraul** [comment]
Current version in master is 2.1.9 (it should say this on the plugins list). Also please make sure Mantis Core Formatting plugin is enabled.

**Comment by spmeesseman** [comment]
crap im several versions behind (2.1.6)...  im not used to someone making so may updates in such a short amount of time haha, a lot of these plugins are unmaintained it seems.  ill install the latest and see

**Comment by bkraul** [comment]
haha...so yeah, I go in spurts, when I have time to address. And a few guys help out with PRs. You can either try to keep your clone up to date, or you can check out the releases page as well.

**Comment by spmeesseman** [comment]
yeah that was it.  Im really sorry to have wasted your time.

Thank you for your contributions!  In return I have 6 plugins I made that I'm about to transfer to mantisbt-plugins, I hope you can find one or some of them useful when I can get them up :)

**Comment by bkraul** [comment]
No issues man, thanks for contributing. Closing issue.
