### ISSUE TITLE
Github tag 2.1.10 and 2.1.11

### ISSUE THREAD

**Issue by kuz30** [mantisbt-plugins/BBCodePlus#85]
mantisbt-plugins/BBCodePlus releases / tags are missing for 2.1.10 and 2.1.11 (https://github.com/mantisbt-plugins/BBCodePlus/releases)
It is sufficient for build pipeline based on releases, where only 2.1.9 is available (https://github.com/mantisbt-plugins/BBCodePlus/archive/v2.1.9.tar.gz)

**Comment by bkraul** [comment]
Tags are now available.

**Comment by kuz30** [comment]
Many thanks, really fast!
