### ISSUE TITLE
including of javascript from cloudfare does not depend from config parameter cdn_enabled

### ISSUE THREAD

**Issue by FSD-Christian-ADM** [mantisbt-plugins/BBCodePlus#88]
the external resource https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js is always loaded even when cdn_enabled is set to OFF.

in Mantis core this is used for example at core/html_api.php in the function html_css()

**Comment by bkraul** [comment]
@FSD-Christian-ISS can you let us know how this relates to BBCodePlus? There is not a dependency for this on the plugin itself, as far as I can tell...

**Comment by FSD-Christian-ADM** [comment]
@bkraul see line 108 in BBCodePlus.php
the function adds that js include to the html headers

**Comment by bkraul** [comment]
Got you, thanks. So basically what you are recommending is we ship a local copy and respect the cnd_enabled global preference.

**Comment by FSD-Christian-ADM** [comment]
@bkraul 
yes, that would be the best option. for cases the remote file isn't available mantis would take a really long loading time and forced includes from external sources is always a security issue
thanks!
