### ISSUE TITLE
Preview not working with BBCodePlus 2.1.17

### ISSUE THREAD

**Issue by steefzz** [mantisbt-plugins/BBCodePlus#99]
Hello bkraul,

I recently update the plugin to 2.1.17 (running on Mantis 2.24.1 with php 7.2.31)
However, i noticed that the preview button (green check mark) doesn't show a preview anymore.

When i click the button, nothing happens.

Tried with Chrome and Edge (also cleared cache)
I don't see anything happening in apache2 error log when clicking it.

Anything else i can do?

Thanks in advance.

Stefan

**Comment by bkraul** [comment]
Check the console on developer tools (press F12 to bring it up, then refresh the page, and try to press on the preview button).

If there any Javascript or CSP errors it will tell you. 

I don't seem to have issues with it, but I will double check.

**Comment by bkraul** [comment]
I just checked on my environment, and there don't seem to be any issues:

![Preview](https://user-images.githubusercontent.com/14616851/86912437-97ca9780-c0e2-11ea-8de2-e0267017d7b5.gif)

**Comment by steefzz** [comment]
Hi, thanks for your quick reply

I checked and noticed the following error:

```
plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:224 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-60IhEVpy-MASUq0j' 'self'".

    at HTMLLIElement.<anonymous> (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:224)
    at HTMLLIElement.dispatch (jquery-2.2.4.min.js:3)
    at HTMLLIElement.r.handle (jquery-2.2.4.min.js:3)
```

**Comment by bkraul** [comment]
It seems there is an issue with your content security policy. What version of mantis are you using? I know there have been some issues in the past with the default CSP. I am currently using the default csp (plus the exceptions BBCodePlus adds for operation), without problems.

![image](https://user-images.githubusercontent.com/14616851/86919423-d023a300-c0ed-11ea-9e9d-fb0c1ac4bda0.png)

**Comment by steefzz** [comment]
We are using 2.24.1
![image](https://user-images.githubusercontent.com/13647902/86919970-4c87a780-c129-11ea-8fd8-131e132b435b.png)

I'll have a look in to CSP (what it is and how it works ;) ) 

I will report back here.

Thanks

**Comment by bkraul** [comment]
I'm curious about that `nonce-60IhEVpy-MASUq0j` entry in the self-eval rule. I don't think it is part of the original Mantis installation. Do you have additional mantis plugins enabled? Or are you using a browser adding, things like TamperMonkey or GreaseMonkey?

**Comment by bkraul** [comment]
I have found more information about `nonce`, and might be able to make changes to the plugin to securely allow execution of `unsafe-eval` for proper plugin functioning. Will report back in a while.

**Comment by bkraul** [comment]
Could you try my [`develop`](https://github.com/bkraul/BBCodePlus/archive/develop.zip) version and see if the behavior is addressed? I'd like to  make sure before I merge #100

**Comment by steefzz** [comment]
Hi,

Thanks again for your quick reply.
Just updated. Unfortunately the issue still remains, see attached screenshot (now with extra info):
![image](https://user-images.githubusercontent.com/13647902/86927027-16e7bc00-c133-11ea-8cf6-d7bc87fd935d.png)

Additionally, we also use quit a lot of plugins as wel:
![image](https://user-images.githubusercontent.com/13647902/86927208-557d7680-c133-11ea-90dc-69cc77227fd2.png)

**Comment by bkraul** [comment]
Thanks. Back to the drawing board, then. I believe I can replicate the errors using Chrome, so that should make it easier for me to try to correct this.

**Comment by steefzz** [comment]
Thanks, if i can do/test anything just let me know

**Comment by bkraul** [comment]
Allright please redownload the [`develop`](https://github.com/bkraul/BBCodePlus/archive/develop.zip) package, and make sure to clear your cache.

**Comment by steefzz** [comment]
Yes man, awesome! It's correct now (error concerning CSP also gone now):
![image](https://user-images.githubusercontent.com/13647902/86953100-38a56b00-c154-11ea-9fea-a2b98034317d.png)

Thanks!
